version: '3'
services:
  sender:
    build:
      args:
        machinepourpouse: "sender"
    command: [ "python", "./sender.py" ]
  receiver:
    build:
      args:
        machinepourpouse: "receiver"
    command: [ "python", "./receiver.py" ]
    ports:
      - "5000"
