version: '3'
services:
  receiver:
    depends_on:
      - sender
    links:
      - "sender:sender"
    build:
      args:
        machinepourpouse: "receiver"
    command: [ "python", "./receiver.py" ]
  sender:
    build:
      args:
        machinepourpouse: "sender"
    command: [ "python", "./sender.py" ]


