version: '3'
services:
  receiver:
    build:
      args:
        machinepourpouse: "receiver"
    command: python3 -u ./receiver.py
    ports:
      - "5000:5000"
  sender:
    links:
      - "receiver:receiver"
    build:
      args:
        machinepourpouse: "sender"
    command: python3 -u ./sender.py